# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c30d334754e8304b63f67c60dfc98ad32498fcb7fcad88748ca70b1ae6e058ba04c45093a41b185267f8144a28468a3f219787d17a2ff9e478434b359584a0f

test:
  secret_key_base: 9a2752b20457285ed384641ea62c46ec6fd9c3805b9896ec2457d0de51b04c14f4b380d834b15df68a58c9646464d64e9d818f932784483d47f4001dfbe50560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
